### ISSUE TITLE
$route->handler and  $route->handler() naming

### ISSUE THREAD

**Issue by iotch** [auraphp/Aura.Router#105]
Hello.

I'm a bit confused about 'handler' method and property names in `Route` class (3.x).
Test route:

``` php
$map->route('test.route', '/', function($request, $response) { 
    return $response; 
});
```

When the route matched and `$route->handler` filled with callable,

```
Closure Object
(
    [parameter] => Array
        (
            [$request] => 
            [$response] => 
        )

)
```

it is confusing when you try to call it directly via `$route->handler($request, $response)` because `Route::handler()` exists and gets called, instead of Closure Object. So we have to put `$route->handler` contents into variable and call it then or use `call_user_func($route->handler, $myParam)` to run that callable.

Should either `$route->handler` or `$route->handler()` be renamed to avoid it? Or this is expected behavior?

**Comment by harikt** [comment]
Good catch. Seems `handler` can be renamed to `handle` . (Talking about https://github.com/auraphp/Aura.Router/blob/3.x/src/Route.php#L349).

**Comment by pmjones** [comment]
The `$handler` property is the handler for the route. You get the handler by asking for it, the way you get the other values in the Route object by asking for them; that is, by getting the property. The methods are setters, not invokers.
