### ISSUE TITLE
[NFR 3.x] Load route definitions from array

### ISSUE THREAD

**Issue by iotch** [auraphp/Aura.Router#106]
Hello.
Will be great to have the ability to load route definitions from an array, like so:

``` php
$routes = [
    'route' => [
        '__arguments' => ['test.route', '/{controller}{/action,id}', function($request, $response, $next) { 
            return $next($request, $response);
        }],
        'tokens' => [
            '__arguments' => [
                [
                    'id' => '\d{2,}'
                ]
            ]
        ]
    ]
];

$routerContainer = \Aura\Router\RouterContainer('/', $routes);
```

This will lead to easier configuration within the DI container, IMO.
Thanks!

**Comment by harikt** [comment]
May be related to https://github.com/auraphp/Aura.Router/issues/64#issuecomment-57068121

**Comment by iotch** [comment]
@harikt, thanks for the reference!

Currently I'm using this approach (sample dispatcher class code):

``` php
    public function __construct(string $basepath, array $routes = [])
    {
        $this->routerContainer = new RouterContainer($basepath);

        $this->compileRoutes($routes);
    }

    protected function compileRoutes()
    {
        try {
            if(! empty($this->routes)) {
                $this->routesMapper($this->routes, $this->routerContainer->getMap());
            }

        } catch(\Throwable $t) {
            throw new Exception('Failed to load routes from definitions array', null, $t);
        }
    }

    protected function routesMapper(array $arr, $target, string $args_key = '__arguments')
    {
        foreach($arr as $key => $val) {           
            if($key !== $args_key) {
                $arguments = $val[$args_key] ?? [];
                $target = $target->$key(...$arguments);                     
                $this->routesMapper($val, $target, $args_key);
            }
        }
    }
```

It's about 15% slower, than regular routes setup, but that's ok. As far as I can tell it works with all `Map` public methods,but I may miss something, of course.

**Comment by pmjones** [comment]
Sorry @iotch, I'm going to turn this one down for the same reason I gave in https://github.com/auraphp/Aura.Router/issues/64#issuecomment-57068121 ...

> It ended up being quite unwieldy. Among other things, it became difficult to construct the array descriptor in a way that covered Every Possible Condition Ever. It's not the kind of thing I'd want to try my hand at again.

... but with the same "PR welcome" followup:

> Having said that, if you want to add a method on the RouterFactory that takes an array descriptor of the kind you mention and translates it into a RouteCollection for the Router, I will be happy to review it. I warn you, though, it's going to be quite the undertaking.

So if you want to submit a PR that does what you're looking for, I'll be happy to review it.
