### ISSUE TITLE
support optional params at the beginning of the path

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Router#108]
From the http://blog.alejandrocelaya.com/2015/09/12/my-first-approach-to-zend-expressive/

> I needed routes to support optional params at the beginning of the path (the language). Neither Aura.Router or FastRoute do it, so I had to stick with ZF2's router .

Use case was `<lang>/blog` . If no lang the default should take `en` without `/en/blog` but route from `/blog` .

**Comment by pmjones** [comment]
This is only the second time it's come up in 18 months (the last time was #35). It just doesn't seem to be that much of a "required" feature.

**Comment by harikt** [comment]
Didn't recalled.
