### ISSUE TITLE
Matching RequestTarget vs URI Path (3.x)

### ISSUE THREAD

**Issue by jakejohns** [auraphp/Aura.Router#109]
The Matcher current matches against the value of `$request->getUri()->getPath();`.
Is this preferable to using `$request->getRequestTarget()` ?

**Comment by pmjones** [comment]
Good question. What's the difference between the two? (I ask from ignorance.)

**Comment by jakejohns** [comment]
Trying to figure out the difference as well. (Honestly, I was hoping you were
going to chime in with some expert analysis of the difference and why the
current method is so)

I believe `getRequestTarget` defaults to `$uri->getPath() . '?' . $uri->getQuery()`

The thing that tripped me up was that doing `$request->withRequestTarget(...)`
wont affect the route as `withRequestTarget` doesn't change the URI instance.

That seemed a little odd to me, but i guess the alternative is something like 
`parse_url($request->getRequestTarget(), PHP_URL_PATH)` which also feels not
quite right maybe.

Possibly relevant [FIG: 1.4 Request Targets and URIs](http://www.php-fig.org/psr/psr-7/#1-4-request-targets-and-uris)

**Comment by pmjones** [comment]
Since `getRequestTarget()` includes the query string, and since the router only routes on the the path, it seems like `getPath()` is the right thing. Let me know if you discover otherwise.
