### ISSUE TITLE
Add an option to chose order of match route (3.x)

### ISSUE THREAD

**Issue by gsouf** [auraphp/Aura.Router#110]
Right now route matcher matches routes in FIFO order.

For some reasons you might want the matcher to match in FILO order.

I propose to add a way for the matcher to know how he should process. At a first sight, it would be very easy to implement just by reversing this loop: https://github.com/auraphp/Aura.Router/blob/57a806686ea349747b42c9cb0f97c43ca1672052/src/Matcher.php#L117

That could look like:

```
   $routerContainer->getMatcher()->setReverseMatchOrder(true);
```

What's your opinion?

**Comment by gsouf** [comment]
ping @harikt  @pmjones

**Comment by harikt** [comment]
@gsouf this is possible. Not sure whether that is really need though. Send a PR if you are really in need for it. Not sure what @pmjones think about this.

**Comment by gsouf** [comment]
@harikt before writing any PR I want to know your opinion, that kind of new feature needs to be discussed i think

**Comment by pmjones** [comment]
After thinking about this for some time, I think the answer is "it's not needed." I don't think any router anywhere does LIFO matching, and honestly I can't imagine needing it. If you want to write up a use case, we can re-open the issue and discuss it some more.

**Comment by gsouf** [comment]
@pmjones I actually have a use case that can be discussed. This case is a bit edgy indeed, in a real web application that would probably never be useful. But in my case it is. Here is the case:

I use the aura router to unit test API client with PSR-7 requests
In the router I have some default routes. Let's say:

``` php
$map->get("route1", "/route1", [...]);
$map->get("route2", "/route2", [...]);
```

Latter in the application some route may be overwritten by the user:

``` php
$map->get(null, "/route1", [...]); // This will never match because the previous /route1 matches before
```

An obvious workarround is to store everything in an associative array that will keep only 1 trace of each route , then create the router on demand but it requires to also store all the thing that are unique in the matching (uri, method, ...) also the flexibility of route grouping, etc...

An other workarround would be to write my own router class that extends the original and that provides reversed routing. But if this feature can be shared, it's better.

**Comment by pmjones** [comment]
Overwriting a route later in the setup process does not mean changing to LIFO will work as expected. What you want in that case is to replace the existing route, not to check the routes in reverse order.
