### ISSUE TITLE
Custom validation for individual route parameters

### ISSUE THREAD

**Issue by djmattyg007** [auraphp/Aura.Router#112]
It would be nice if it was possible to use something other than a regex to validate individual route parameters. Ideally, this would take the form of a callable that is passed the value and returns true or false. For example, I'm using the Composer Semver package elsewhere in a project, and am using version numbers as part of the URL. Ideally I'd just be able to wire up the two.

**Comment by pmjones** [comment]
I admit this sounds interesting. If you want to send a PR, I'll be happy to review.

**Comment by gsouf** [comment]
:+1:

**Comment by pmjones** [comment]
Fixed by #120

**Comment by pmjones** [comment]
Fixed by #120

**Comment by djmattyg007** [comment]
Perhaps it's time for a new release?

**Comment by pmjones** [comment]
Dealing with #138 now -- then a release :-)

**Comment by pmjones** [comment]
Oh, and thanks for your unbelievable patience on this.

**Comment by djmattyg007** [comment]
I'm in no rush. The project I was working on when I posted this was basically cancelled. Thanks for your tireless efforts to improve this software :)

**Comment by pmjones** [comment]
> I'm in no rush.

Much appreciated. So little time, so many obligations to prioritize.
