### ISSUE TITLE
How do I define the $request variable?

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Router#113]
Hi, 

I got an email asking about version 3.x of router.

> How do I define the $request variable?

I did pointed to https://github.com/zendframework/zend-diactoros

I will look into how I can fix it when I get sometime.

Thank you.

**Comment by thinsoldier** [comment]
I have the same problem. Are you saying that zend-diactoros is a requirement for Auro.Router to work? Is zend-diactoros the thing I'm supposed to use to create the $request variabled used in the example code?

**Comment by thinsoldier** [comment]
Argument 1 passed to Aura\Router\Matcher::match() must be an instance of Psr\Http\Message\ServerRequestInterface
Where do I get an object that implements this interface? Is it a different Aura package? Is it a package from a different framework/library elsewhere in the php community?

**Comment by pmjones** [comment]
/me nods

Basically, the Router needs a ServerRequest object. The Router is not in charge of creating this; something else must provide it. Zend Diactoros is one package that provides it; I am not aware of others but they may exist.

**Comment by harikt** [comment]
@thinsoldier Aura.Router v3 need a psr-7 implementation. Version 2 don't need anything. 

You can find other psr-7 implementations https://packagist.org/providers/psr/http-message-implementation . Some of them are not really implementations though. People confuse adding the same :-1: to get more attraction to the package.

**Comment by harikt** [comment]
Similar questions regarding `$request` object #119
