### ISSUE TITLE
Fully working example code?

### ISSUE THREAD

**Issue by thinsoldier** [auraphp/Aura.Router#119]
https://github.com/auraphp/Aura.Router/blob/3.x/docs/getting-started.md

Having a hard time getting this code to work. Would have helped if it specifically mentioned needing \Zend\Diactoros\ServerRequest and a link to download it.

```
$request = \Zend\Diactoros\ServerRequestFactory::fromGlobals();
$route = $matcher->match($request);
```

I'm presently stuck at

```
$callable = $route->handler;
$response = $callable($request);
```

Error: Warning: Missing argument 2 for {closure}(), called in ... ...  on line 15.
The error refers to:

```
$map->get('blog.read', '/blog/{id}', function ($request, $response) {
    $id = (int) $request->getAttribute('id');
    $response->body()->write("You asked for blog entry {$id}.");
    return $response;
});
```

Apparently `$response = $callable($request);` should have a 2nd parameter but I'm not sure what and the example code does not have a 2nd parameter.

Please see my code at: https://github.com/thinsoldier/aura-router-test

I'm pasting the code exactly from your "Getting Started" and trying to get its basic functionality working.

Also, and this might just be my machine or web server, but at times this example code takes 11 seconds to run.

**Comment by harikt** [comment]
Hi @thinsoldier ,

The code you have in the repo needs a few fix. This is what I changed and tested the url.

``` php
@@ -12,7 +12,7 @@ $map = $routerContainer->getMap();

 $map->get('blog.read', '/blog/{id}', function ($request, $response) {
     $id = (int) $request->getAttribute('id');
-    $response->body()->write("You asked for blog entry {$id}.");
+    $response->getBody()->write("You asked for blog entry {$id}.");
     return $response;
 });

@@ -24,7 +24,7 @@ $route = $matcher->match($request);

 if( false === $route ){ echo "route not found for current url"; }

-var_dump($route);
+// var_dump($route);

 #var_dump($route->attributes);

@@ -38,6 +38,5 @@ foreach ($route->attributes as $key => $val) {

 $callable = $route->handler;
 $response = $callable($request, new \Zend\Diactoros\Response);
-
+echo $response->getBody();
```

We will try to improve the docs.

Thank you for the feedback.

**Comment by thinsoldier** [comment]
Thanks harikt. Works now.

**Comment by harikt** [comment]
@thinsoldier you can also echo the header of the response. Please don't forget to use that.
