### ISSUE TITLE
index.php example needed

### ISSUE THREAD

**Issue by cxj** [auraphp/Aura.Router#124]
I keep seeing requests in the #auraphp IRC channel for help with Aura.Router, especially with release 3.  Mostly people are confused about how to actually use it, because many competing products do so much more.  What's really needed is an example of usage from a DOCROOT/index.php point of view in the documentation someplace.

**Comment by harikt** [comment]
Hi @cxj ,
I have added a PR https://github.com/auraphp/Aura.Router/pull/123 to solve the question about `$request` .

We could probably add more.

EDIT : By the way thanks for all your help in the #auraphp irc channel.

**Comment by pmjones** [comment]
You guys are awesome. Thanks so much.

@harikt I merged #123; does that "solve" this issue for now?

**Comment by harikt** [comment]
@pmjones yes, we could probably add a blog post regarding the full usage and link to it if needed. Or do you think it is good to have in the doc itself ?

**Comment by harikt** [comment]
@cxj closing this for the current time. If you think the examples are still not correct please re-open the same.

Thank you.
