### ISSUE TITLE
enhancement request : map prefixes

### ISSUE THREAD

**Issue by udf2457** [auraphp/Aura.Router#125]
Howdy.

At the moment, on my dev box, a full URL could look something like the following: 
`http://10.10.10.10/example/www/public/index.php/blog/49`

This means, that at present I have to do the following, otherwise I get a 404: 
`$map->get('Example\Misc\Demo','/example/www/public/index.php/blog/{id}');`

What would be cool is if I could say
`$map->urlprefix('/example/www/public/index.php');
$map->get('Example\Misc\Demo','/blog/{id}');`

Similarly, if I set an alias on my server of '/bob' pointing to '/example/www/public/index.php', it would be equally cool to be able to do:
`$map->urlprefix('/example/www/public/index.php');
$map->urlalias('/bob');
$map->get('Example\Misc\Demo','/blog/{id}');`

**Comment by harikt** [comment]
I believe you could do this now also. See https://github.com/auraphp/Aura.Router/blob/c638e569365447fa1ee1a3727a858ad45a2facb5/src/RouterContainer.php#L120 . Pass `basepath` to the container.

**Comment by pmjones** [comment]
@udf2457 Did @harikt answer your question here?

**Comment by pmjones** [comment]
Closing from lack of feedback; @udf2457 if you feel the need, please ask for it to be reopened.
