### ISSUE TITLE
Install without composer ?

### ISSUE THREAD

**Issue by ghost** [auraphp/Aura.Router#126]
How to install standalone version of this router ? 
I try with:

```
use Aura\Router\RouterContainer;
require_once __DIR__.'/vendors/Aura/Router/RouterContainer.php';
$routerContainer = new RouterContainer();
$map = $routerContainer->getMap();
```

but i get: : Class 'Aura\Router\Map' not found in  .... error.

**Comment by harikt** [comment]
Hey @val4o0o0 ,

v3 is using certain dependencies so you need to install via composer. 

## Alternatively :
1. Download the package to local system and install the dependencies. When uploading do upload the `vendor/` folder which contains the dependencies.
2. If you don't like the 1 st approach , download one of the 2.x release  https://github.com/auraphp/Aura.Router/releases/tag/2.3.0 . Please look at the 2.x documentation on its usage.
