### ISSUE TITLE
Query Params and Fragments in route path

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Router#130]
I was looking at https://github.com/zendframework/zend-expressive/issues/325 . 

It was basically an issue regarding whether it is routers responsibility or the url helpers responsibility to add query params / fragment to the route path.

So this actually reminds me of https://github.com/auraphp/Aura.Router/pull/129 which we were trying to build the generator.

What do you guys think about the same ?

Thank you.

**Comment by pine3ree** [comment]
@harikt 
Hello, as I wrote in my comments https://github.com/zendframework/zend-expressive/issues/325#issuecomment-252442786 i believe the router should be query-string agnostic.
The purpose of a router is to match incoming paths to defined routes and build paths from route name and params.
The problem in https://github.com/zendframework/zend-expressive/issues/325 is about the urlHelper which, as the name itself already tells us, should in my opinion deal with more than just the path. Adding supports for several router options + query params is making the signature too messy.

kind regards

**Comment by harikt** [comment]
Hey @pine3ree ,

Thanks for taking your time checking the issue. I am also looking at https://github.com/auraphp/Aura.Router/pull/129 which is a view helper . Please see the PR.

**Comment by harikt** [comment]
@pine3ree I have created another PR based on your suggestions on expressive. In case if you are interested let me know what you think about this. https://github.com/auraphp/Aura.Router/pull/131

Thank you for your interest and time.

**Comment by pmjones** [comment]
Closing this as "fixed" by #129.

**Comment by gsouf** [comment]
@harikt even after browsing different related issues, I'm not sure to fully get how this issue is fixed. 

Can you show an exemple of how to use query params with the generator, please?

**Comment by harikt** [comment]
@gsouf 

https://github.com/dlundgren/Aura.Router/blob/cf18054890ca5650c77d6479992354d7ce42387b/docs/other-topics.md#route-helpers

```php
<?php
echo $urlHelper('blog.read', 'my title') . '?' . http_build_query($data);
```

See http://php.net/manual/en/function.http-build-query.php

**Comment by gsouf** [comment]
Thank you @harikt !

Then, the generator itself is not aware about query string and we have to add it by concatening by ourselve.

**Comment by harikt** [comment]
@gsouf yes.
