### ISSUE TITLE
Catchall: Invalid callable provided

### ISSUE THREAD

**Issue by ghost** [auraphp/Aura.Router#135]
Hi,

How to put catchall in place ?
When I try, if I go to my site I get the error: "Invalid callable provided".

Regards

**Comment by harikt** [comment]
Can you show an example how you get this error ?

catchall docs for reference : https://github.com/auraphp/Aura.Router/blob/6c0f3c41d31d3b9a0348b8234ec83bbf1479940d/docs/other-topics.md#catchall-routes

**Comment by ghost** [comment]
I wrote exactly the same code from the documentation (by copy / paste)
```
$map->get('catchall', '{/controller,action,id}')
    ->defaults([
        'controller' => 'index',
        'action' => 'browse',
        'id' => null,
    ]);
```

And how can I manage this rule with AuraDispatcher ? I did not find any example for their combination.
Sorry If my question is stupid. I just begin with this framework.

**Comment by harikt** [comment]
```php
$map->get('catchall', '{/controller,action,id}')
    ->defaults([
        'controller' => 'index',
        'action' => 'browse',
        'id' => null,
    ]);
```

the above code is adding a route : http://auraphp.com/packages/3.x/Router/getting-started.html#1-4-1-1

You want to then match a Route : http://auraphp.com/packages/3.x/Router/getting-started.html#1-4-1-2 

I have a video tutorial https://www.youtube.com/watch?v=DA60mYS-YoM and the gist : https://gist.github.com/harikt/243fb272a64761a089309b3338d9bee0 for the Router.

Pay attention to handler : https://gist.github.com/harikt/243fb272a64761a089309b3338d9bee0#file-index-php-L37 .

```php
var_dump($handler); 
```

and see what it produce. It will be an array or closure depending on what you have added to route.

> And how can I manage this rule with Aura.Dispatcher ? 

First instantiate the dispatcher : https://github.com/auraphp/Aura.Dispatcher#closures-and-invokable-objects

You may want to set the object to the dispatcher as 

```php
<?php
use Aura\Dispatcher\Dispatcher;

// Router code

$dispatcher = new Dispatcher;
$dispatcher->setObjectParam('controller');
$dispatcher->setMethodParam('action');

// this code may change according to your idea 

$controllerClass = ucfirst(strtolower( $route->handler['controller'] )) . 'Controller';

$dispatcher->setObject($route->handler['controller'], new $controllerClass());

// Only if there is a matching Route 

$params = $route->handler;

$result = $dispatcher($params);
echo $result;
```

> I did not find any example for their combination.

Sorry none have been written :-( .

> Sorry If my question is stupid. I just begin with this framework.

No problem, but if you read it very carefully you may get the idea I believe.

This may help to start I believe.

**Comment by ghost** [comment]
Thank you for all this details.

**Comment by harikt** [comment]
Closing for the issue seems addressed. 

If you have further questions you can write to google groups or in stackoverflow. Links over : http://auraphp.com/community/ 

Happy to help.
