### ISSUE TITLE
Short video tutorial

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Router#136]
Hi Paul, 

I have created a video tutorial on v3 router integration : https://www.youtube.com/watch?v=DA60mYS-YoM

Gaurav Grover https://www.youtube.com/watch?v=DA60mYS-YoM&lc=z13yxbigcryeg5rsl231inhzcq3nz1lbr04 was mentioning it will be nice to link it from docs.

I will send a PR if you think so. May be to README.md ?

**Comment by pmjones** [comment]
PR!

**Comment by harikt** [comment]
Closing for there is PR for the same.

**Comment by koriym** [comment]
@harikt  Good job ! I watched !

**Comment by harikt** [comment]
@koriym thank you. Wasn't much prepared, but lots of request to do the same. So made it some what quickly. I may want to write a transcript before I start next time ;-) . More time, more efforts , but will look much more better I believe.

**Comment by koriym** [comment]
@harikt Update composer ! xdebug warning will be disappeared.

**Comment by koriym** [comment]
@harikt Your explanation is clear. I think the video helps to understand people more easily. It is time consuming job. Really good !

**Comment by harikt** [comment]
Thank you very much @koriym .
