### ISSUE TITLE
setIsMatchCallable for version 3.x

### ISSUE THREAD

**Issue by Ricael** [auraphp/Aura.Router#138]
Hello,

I recently upgraded my project from version 2.x to 3.x of aura router. 
In the previous version I used the method:
`->setIsMatchCallable(function(array $server, \ArrayObject $matches)`

but It seems it dissapeared (or it is hidden within other method). Could you point me where it is?

In case the feature is not available for 3.x, could it be possible to be updated with it?

Thanks !

**Comment by harikt** [comment]
You can add custom rule. http://auraphp.com/packages/3.x/Router/custom-matching.html#1-4-6 . The problem here is you may want to detect the route itself for it is generic rule than rule for only a Route.

Hope that helps.

**Comment by Ricael** [comment]
This could be a solution but I'm not sure if it will work the same way than previous versions:

The first problem is that in my scenario, some rules need to pass the "isMatch" call (not all) and that method is not the same between these routes. This could be solved with different custom rules.

The second is that the Route project that I am developing is a package that other projects will use and each of those have their own set of routes (and "match" functions) so in this case I should make those custom rules on each class (big effort) or create them on runtime? (PITA)

That's the real deal. In the previous version I could use setIsMatchCallable() and worked like a charm, but on the 3.x version, its not that easy... am I correct?

Thanks for your time and help.

**Comment by harikt** [comment]
Hi @Ricael , 

Thank you for reporting your use case.

I have a question regarding

> The second is that the Route project that I am developing is a package that other projects will use and each of those have their own set of routes (and "match" functions) so in this case I should make those custom rules on each class (big effort) or create them on runtime? (PITA)

Probably, I may have not understood it clearly. But if my understanding is correct doesn't one rule can help all the projects route you are using for the single route ? It is basically a callable so you don't need to create multiple classes itself. https://github.com/auraphp/Aura.Router/blob/46cccea7d1ae9eeac611a527898089665567959d/src/Rule/RuleIterator.php#L66

**Comment by harikt** [comment]
If you have some code to show happy to look regarding your use case for project.

**Comment by Ricael** [comment]
Hi again, I'll try my best to explain:

I load a set of routes in each project, MyRouter class is the core of all those, that uses aura/router.

Routes are like these:

**routes_1.yml**
```
home :
    description : 'Main entry point'
    rule : '/{index}$'
    options:
      params :
        index : "(index(\.php)?(\/)?)*"
      values :
        controller : 'cover'
        action : 'index'
      method : [GET]
      secure : false
      routable : true
      is_match: 'Path\To\Class_1::Method_1'
//SOME OTHER ROUTES HERE
```

**routes_2.yml**
```
home :
    description : 'Main entry point'
    rule : '/{index}$'
    options:
      params :
        index : "(index(\.php)?(\/)?)*"
      values :
        controller : 'cover_special'
        action : 'index'
      method : [GET]
      secure : false
      routable : true
      is_match: 'Path\To\Class_2::Method_2'
//SOME OTHER ROUTES HERE
```
Each project, loads with Composer(dependency manager) the "core" that is MyProject and uses it as router. Each different project has its own "routes.yml" and "is_match" class & methods

Previously I called, for example:
```
$content = loadFromYml("file.yml");
$this->router->add($rule, $content['rule'])
                ->addTokens($content['options']['params'])
                ->addValues($content['options']['values'])
                ->setRoutable($content['options']['routable'])
                ->setSecure($content['options']['secure'])
                **->setIsMatchCallable($content['options']['is_match']);**
```
With 3.x im a little bit lost, and I dunno how to do the same.

Thanks in advance !

**Comment by harikt** [comment]
Sorry for the api changed a bit. But I am sure we could probably bring the feature back.

We could add `setIsMatchCallable`  to Route as earlier what we did, and can check from https://github.com/auraphp/Aura.Router/blob/46cccea7d1ae9eeac611a527898089665567959d/src/Matcher.php#L119 . 

So this should actually work without adding a Rule which we need to define / look up the path / being called by all routes.

@pmjones is there any other way you know how to resolve this issue ? Else it will be hacks though ;-)

Thank you.

**Comment by harikt** [comment]
Hi @Ricael , 

I have made https://github.com/auraphp/Aura.Router/pull/139 which will fix your issue hopefully I guess. Looking for your feedback and others.

If everything goes fine, we can release this in 3.1.0 .

If you think any other feature is missing you can also request for the same. Or come with a PR.

Thank you.

**Comment by Ricael** [comment]
Thank you very much, that was fast!

I'll try it and write some feedback soon. 

This is the only _feature_ that was missing for me, in version 3.x.

Thanks again!

**Comment by pmjones** [comment]
Looking at this, and at #139 from @harikt, it seems to me the feature addition has to be in two pieces:

1. On the route object, add a property for `customMatch(callable $customMatch)` (or some similar name).

2. Add a new rule class, `CustomMatch` (named for the route property) that invokes the `$route->customMatch` callable and returns a boolean result.

That should keep things more cleanly separated.

As an alternative, @Ricael, you could [write a custom Route class](https://github.com/auraphp/Aura.Router/blob/3.x/docs/custom-maps.md#extending-the-route-class) that does the above, and then [write a custom Rule class](https://github.com/auraphp/Aura.Router/blob/3.x/docs/custom-matching.md) to handle it.

Does all that make sense to everyone?

**Comment by harikt** [comment]
Yes this makes more sense @pmjones . I haven't thought about it . Thanks and nice approach.

**Comment by pmjones** [comment]
@harikt Good deal. :-)

@Ricael Do you feel comfortable customizing the Route and Rule objects yourself, for your own project?

**Comment by pmjones** [comment]
@Ricael Ping -- is this still something you want in the "core" or are you comfortable building it for your own specific project?

**Comment by Ricael** [comment]
Well I preffer this to be a core feature IMHO, and use it straightforward. 
If not, I will manage to make it work in 3.x. Atm I am using it on 2.x and works like a charm... I really like this feature, but also I understand Its not a mandatory update or a fix needed.
My two cents here, anyway I really appreciate your help, effort and will.
Thanks again.
