### ISSUE TITLE
Document example codes not working.

### ISSUE THREAD

**Issue by cwhsu1984** [auraphp/Aura.Router#142]
`PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getBody() on null`
And it turns out that this [had been fixed before](https://github.com/auraphp/Aura.Router/issues/119)
Please fix it so someone who wishes to try aura.router will be able to use it.

**Comment by cwhsu1984** [comment]
I will just leave one that I just complete.

```
<?php

include __DIR__.'/vendor/autoload.php';

use Aura\Router\RouterContainer;

# Add a route
# aura library-specific container
$routerContainer = new RouterContainer();

# get Map from container
$map = $routerContainer->getMap();

# A $name (for when you need to generate link from the route)
# A $path (with optional named token placeholders)
# An optional $handler (a closure, callback, action object, controller class, etc); if you do not pass a handler, the route will use the $name parameter as the handler.
# $map->method($name, $path, $handler)
$map->get('blog.read', '/blog/{id}', function ($request, $response) {
    $id = (int) $request->getAttribute('id');
    $response->getBody()->write("You asked for blog entry {$id}.");
    return $response;
});

# Match a route
$matcher = $routerContainer->getMatcher();

# generate a request object from Zend\Diactoros
$request = Zend\Diactoros\ServerRequestFactory::fromGlobals(
    $_SERVER,
    $_GET,
    $_POST,
    $_COOKIE,
    $_FILES
);

# Psr\Http\Message\ServerRequestInterface $request
$route = $matcher->match($request);

if ($route) {
    # dispatching a route
    # transfer attribute to request
    foreach ($route->attributes as $key => $val) {
        $request = $request->withAttribute($key, $val);
    }

    # get the handler and call handler to process request
    $callable = $route->handler;
    $response = $callable($request, new \Zend\Diactoros\Response);
    echo $response->getBody();
} else {
    # handling match failure
    // get the first of the best-available non-matched routes
    $failedRoute = $matcher->getFailedRoute();

    // which matching rule failed?
    switch ($failedRoute->failedRule) {
    case 'Aura\Router\Rule\Allows':
        // 405 METHOD NOT ALLOWED
        // Send the $failedRoute->allows as 'Allow:'
        http_response_code(405);
        break;
    case 'Aura\Router\Rule\Accepts':
        // 406 NOT ACCEPTABLE
        http_response_code(406);
        break;
    default:
        // 404 NOT FOUND
        http_response_code(404);
        break;
    }
}
```

**Comment by harikt** [comment]
So many issues regarding the same :( . We will try to improve the docs. Sorry for the troubles caused to you.

**Comment by cwhsu1984** [comment]
It's fine with me, but it would really be a pity if someone who wants to use your router but giving up just because of incorrect documentation contents.

**Comment by harikt** [comment]
@cwhsu1984 it was not incorrect documentation. But we have not kept a complete working example. We tried to improve it with adding a video over : https://github.com/auraphp/Aura.Router/tree/34e508e85dc3040a9c1cdca466fe324900a9ea98#documentation . It shows a full integration, and with a gist https://gist.github.com/harikt/243fb272a64761a089309b3338d9bee0 . But I understand people are not finding the exact place where all is covered.

Thank you for the feedback, and I hope we will be able to improve the documentation. If you have any better suggestions do send PR's.

Have a nice day.

**Comment by harikt** [comment]
@cwhsu1984 by the way I guess we need to push for a new release, you would have read the docs from the composer installation I believe. or did you read from the website or where did you read the docs from ?

**Comment by cwhsu1984** [comment]
I read it from the [github](https://github.com/auraphp/Aura.Router/blob/3.x/docs/getting-started.md)

**Comment by cwhsu1984** [comment]
Plus, it would be great if you just add a link of working example in the document, that would save new user a lot of time. Thanks!

**Comment by harikt** [comment]
Closing this for have opened https://github.com/auraphp/Aura.Router/issues/144 to address the same. Feedback appreciated.

Thank you.
