### ISSUE TITLE
Map does not have method 'setDefault'

### ISSUE THREAD

**Issue by cwhsu1984** [auraphp/Aura.Router#143]
"PHP message: PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'Aura\Router\Route' does not have a method 'setDefaults'

https://github.com/auraphp/Aura.Router/blob/3.x/docs/attaching-route-groups.md
```
<?php
$namePrefix = 'blog.';
$pathPrefix = '/blog';
$map->attach($namePrefix, $pathPrefix, function ($map) {

    $map->tokens([
        'id'     => '\d+',
        'format' => '(\.json|\.atom|\.html)?'
    ]);

// removing this part
//    $map->setDefaults([
//        'format' => '.html',
//    ]);

    $map->get('browse', '');
    $map->get('read', '/{id}{format}');
    $map->patch('edit', '/{id}');
    $map->put('add', '');
    $map->delete('delete', '/{id}');
});
?>
```

**Comment by harikt** [comment]
Could you test changing `setDefaults` to `defaults` : https://github.com/auraphp/Aura.Router/blob/34e508e85dc3040a9c1cdca466fe324900a9ea98/src/Route.php#L304 . If so do send a PR with the fix. Will merge it.
