### ISSUE TITLE
The 'Aura\Router\Rule\AbstractRuleTest' class not found

### ISSUE THREAD

**Issue by allowing** [auraphp/Aura.Router#151]
Fatal error: Class 'Aura\Router\Rule\AbstractRuleTest' not found in ***\vendor\aura\router\hold\CookiesTest.php on line 4

**Comment by harikt** [comment]
What are you trying to do?

hold, is not expected to be run.

Regarding `Aura\Router\Rule\AbstractRuleTest`  : present here https://github.com/auraphp/Aura.Router/blob/bfcb784f112a11d3841e609f8a6eae1cbc9b7ae0/tests/Rule/AbstractRuleTest.php .

This will only load on autoload: dev , not on production.

**Comment by allowing** [comment]
Oh, yes, it's ok.

I found it when I use `Doctrine`.

```
orm:schema-tool:create          Processes the schema and either create it directly on EntityManager Storage Connection or generate the SQL output.
```

**Comment by harikt** [comment]
I am still not sure what doctrine has to do with it Aura.Router though. Closing for this is not related to aura, and some other code issue on the app.
