### ISSUE TITLE
Can't use $ to match the end of the string

### ISSUE THREAD

**Issue by therealsamsquanch** [auraphp/Aura.Router#165]
I'm not sure if it's related to #110. I'm trying to match an integer at the end of the URL. 

`$router->get('post', '/post/{id}')->tokens(['id' => '\d+$']);`

Doesn't work with this:

**_/somestring-123_**

There are no error messages, it just doesn't match the string. But it will match this:

**_/123_**

As a workaround I removed my custom match rule and parsed it later on my script, and it does work as intended, it will return **123** on both cases:

`preg_match('/\d+$/', $route->attributes['id'], $matches);`

Sooo, it's not a huge problem, just felt that I should report it in case it's not working as intended or if there's an easy fix.

Thank you!

EDIT: Forgot to mention that I'm using the latest release, 3.1.0

**Comment by ncou** [comment]
did you try with just '\d+' without the dollar sign ? like in the test : https://github.com/auraphp/Aura.Router/blob/3.x/tests/MapTest.php#L46

**Comment by harikt** [comment]
I am not sure this is the real code you have used or not. But the example 

```php
$router->get('post', '/post/{id}')->tokens(['id' => '\d+$']);
```

provided and the matching string is incorrect.

You are checking somestring-digit. But router is using /post/I'd

And you already have that working. So you want to change the route definition accordingly.

**Comment by harikt** [comment]
Hi,

I looked into this and is already possible with some slight changes.

```php
<?php
require_once __DIR__ . '/vendor/autoload.php';

// create a server request object
$request = Laminas\Diactoros\ServerRequestFactory::fromGlobals(
    $_SERVER,
    $_GET,
    $_POST,
    $_COOKIE,
    $_FILES
);

// create the router container and get the routing map
$routerContainer = new Aura\Router\RouterContainer();
$map = $routerContainer->getMap();

$map->get('post', '/post/{randomval}-{id}', function ($request) {
    $response = new Laminas\Diactoros\Response();
    $id = (int) $request->getAttribute('id');
    $randomval = $request->getAttribute('randomval');
    $response->getBody()->write("Hello Post random string $randomval and $id");
    return $response;
})->tokens([
    'randomval' => '[a-z]+',
    'id' => '\d+',
]);

// get the route matcher from the container ...
$matcher = $routerContainer->getMatcher();

// .. and try to match the request to a route.
$route = $matcher->match($request);
if (! $route) {
    echo "No route found for the request.";
    exit;
}

// add route attributes to the request
foreach ($route->attributes as $key => $val) {
    $request = $request->withAttribute($key, $val);
}

// dispatch the request to the route handler.
// (consider using https://github.com/auraphp/Aura.Dispatcher
// in place of the one callable below.)
$callable = $route->handler;
$response = $callable($request);

// emit the response
foreach ($response->getHeaders() as $name => $values) {
    foreach ($values as $value) {
        header(sprintf('%s: %s', $name, $value), false);
    }
}
http_response_code($response->getStatusCode());
echo $response->getBody();
```

See the screenshot for the result.

![image](https://user-images.githubusercontent.com/120454/151350710-71625bf9-6baf-4bc4-8350-110baaf57400.png)

Some examples of these are already over https://github.com/auraphp/Aura.Router/blob/3.x/docs/defining-routes.md#placeholder-tokens-and-default-values.
