### ISSUE TITLE
What's the name paramter for , when defining routes?

### ISSUE THREAD

**Issue by gyaaniguy** [auraphp/Aura.Router#167]
What does exactly 'blog.read', do here ?
$map->get('blog.read', '/blog/{id}')
    ->tokens(['id' => '\d+'])
?>

**Comment by pmjones** [comment]
It's for generating paths to URLs; cf. https://github.com/auraphp/Aura.Router/blob/3.x/docs/generating-paths.md

Please let me know if that helped or not!
