### ISSUE TITLE
Route::clone

### ISSUE THREAD

**Issue by bkdotcom** [auraphp/Aura.Router#169]
[Route::__clone](https://github.com/auraphp/Aura.Router/blob/9167a38a8a9e9ec96667d939e3eaa4b2e7bd5333/src/Route.php#L219-L230)

```PHP
    /**
     *
     * When cloning the Route, reset the `$attributes` to an empty array, and
     * clear the `$failedRule`.
     *
     */
    public function __clone()
    {
        // $this is the cloned instance, not the original
        $this->attributes = $this->defaults;
        $this->failedRule = null;
    }
```

comment says one thing / code does another

```PHP
$map->allows(['GET', 'HEAD', 'POST'])->defaults(array(
    'action' => 'foo',
));
$route = $map->route('test', '/test');
$route->defaults(array('action'=>'not foo'));
var_dump($route->attributes);   // array('action'=>'foo')...  I would expect empty array()
var_dump($route->defaults);     // array('action'=>'not foo')
```

when dealing with routes I don't know if attribute came from url, or some inherited default
If I use `Generator` to build this new route it's going to use the inherited default over the new default

```PHP
$this->attributes = $this->defaults;    // this does NOT reset `$attributes` to an empty array!!
```

**Comment by bkdotcom** [comment]
updating `Route::__clone` && `Route::__get` to the following seems to do the trick for me

```PHP
    /**
     * When cloning the Route, reset the `$attributes` to an empty array, and
     * clear the `$failedRule`.
     */
    public function __clone()
    {
        // $this is the cloned instance, not the original
        $this->attributes = array();
        $this->failedRule = null;
    }

    /**
     * Magic read-only for all properties.
     *
     * @param string $key The property to read from.
     *
     * @return mixed
     */
    public function __get($key)
    {
        if ($key === 'attributes') {
            return array_merge($this->defaults, $this->attributes);
        }
        return $this->$key;
    }
```

**Comment by harikt** [comment]
I agree the comment `When cloning the Route, reset the `$attributes` to an empty array` was a typo. It probably should have mentioned, will use defaults if any or empty start array. Apart from that the code seems working as expected to me.

Next time if possible send a failing test case. It may be helpful.

**Comment by harikt** [comment]
Hi @bkdotcom ,

I know this is an old issue. But just wanted to know if updating doc block as in #190 will remove all the confusions or not.

I will be releasing a 3.2.0 today. In case you are not satisfied with the resolution please do open it.

Thank you for the report.

**Comment by bkdotcom** [comment]
@harikt 
it does!  
Thank you
