### ISSUE TITLE
zendframework/zend-diactoros abandoned, replacement.

### ISSUE THREAD

**Issue by cj-clx** [auraphp/Aura.Router#170]
Running `composer update` for any project which uses `Aura.Router` produces this message:
```
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
```
Can this dependency be updated and tagged?

**Comment by harikt** [comment]
Closing as this already being fixed on 4.x branch. We cannot make a release for 3.x right now.
