### ISSUE TITLE
Routing Error

### ISSUE THREAD

**Issue by waqar-akram-se** [auraphp/Aura.Router#173]
When I request a route like example.com/api/delete/18ZTK6wEto1TTVIVCC1E.png
It throws an error route not found. Please help me to solve this. @pmjones

**Comment by cxj** [comment]
Do you have a route defined something like this to handle it?
```php
$map->get('api.delete', '/api/delete/{file}');
```

Then you'd want to use the value of the `file` token something like this:
```php
$map->get('api.delete', '/api/delete/{file}', function ($request) {
    $file = $request->getAttribute('file');
    $response = new Zend\Diactoros\Response();
    $response->getBody()->write("You asked to delete file {$file}.");
    return $response;
});

// get the route matcher from the container ...
$matcher = $routerContainer->getMatcher();

// .. and try to match the request to a route.
$route = $matcher->match($request);
```

**Comment by waqar-akram-se** [comment]
@cxj yes,  I have defined $map->delete('a.delete', '/api/delete/{file}');

still facing this issue
**Not Found
The requested resource /api/delete/nHugExI4hJoGWd8ZeR77.jpg? was not found on this server.**

**Comment by cxj** [comment]
That sounds almost more like your web server (Apache?) is issuing the message, rather than your PHP code.  That would tend to imply that your code is not rewriting URLs to be handled by your PHP code.

If you _are_ using Apache, and if your main PHP file were named `index.php`, you would want an `.htaccess` file which contained something like the following (or one can configure the equivalent in their server config files):
```
<IfModule mod_rewrite.c>
    # turn on rewriting
    RewriteEngine On

    # turn empty requests into requests for "index.php",
    # keeping the query string intact
    RewriteRule ^$ index.php [QSA]

    # for all files not found in the file system,
    # reroute to "index.php" bootstrap script,
    # keeping the query string intact.
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !favicon.ico$
    RewriteRule ^(.*)$ index.php [QSA,L]
</IfModule>
```

**Comment by waqar-akram-se** [comment]
@cxj  I have configured .htaccess file but still got this error.
What's wrong with this ?
Thanks

**Comment by waqar-akram-se** [comment]
**Resolved** I was using PHP built in server. That won't prohibited  some files extension like(.jpg, jpeg, png, gif ) etc. It throws 404 error Requested page not found.

Thanks @cxj
