### ISSUE TITLE
psr/log dependency is outdated

### ISSUE THREAD

**Issue by jakejohns** [auraphp/Aura.Router#178]
https://github.com/auraphp/Aura.Router/blob/9167a38a8a9e9ec96667d939e3eaa4b2e7bd5333/composer.json#L22

Current version is 3.0
https://github.com/php-fig/log/tags

**Comment by harikt** [comment]
@jakejohns this has been addressed in #177 by @koriym for 4.x .

Please reopen in case you have some difficulties. I am going to close this in good sense. 

Thank you for you attention to details.

**Comment by koriym** [comment]
@harikt Actually, this issue has not been resolved yet! It will be resolved in a new PR.

**Comment by harikt** [comment]
Cool
