### ISSUE TITLE
Abandoned or still active ?

### ISSUE THREAD

**Issue by MadCat34** [auraphp/Aura.Router#179]
See title.

Last PR and last commit on 3.x branch are 3-years old ...

**Comment by koriym** [comment]
Hi.

I just created a 4.x branch to work with the latest PHP. #177

**Comment by harikt** [comment]
Hey @MadCat34 ,

Great timing and thanks @koriym for your attention on the repo. We are revamping.

Thanks for being with Aura.

**Comment by MadCat34** [comment]
Thanks @koriym :0)
