### ISSUE TITLE
When using microframework example, urlencode throws a warning that it's not being passed a string

### ISSUE THREAD

**Issue by gabelerner** [auraphp/Aura.Router#19]
The example suggests to use the key 'controller'  with a value of anonymous function/closure, but later when Route.generate is called, it loops through all the values and calls urlencode on each, throwing a php warning as the anonymous function/closure is not a string (Warning: urlencode() expects parameter 1 to be string).  Don't know if you wish to add to the code or update the microframework docs to resolve this.

**Comment by pmjones** [comment]
I believe this has been fixed. Please reopen if you find it to be otherwise.
