### ISSUE TITLE
Getting Started Documentation

### ISSUE THREAD

**Issue by hamzakubba** [auraphp/Aura.Router#2]
This applies to this library and probably all the others.

It would be very helpful to people unfamiliar with aura to have a new section before the "Basic Usage" section called "Getting Started: aura.router as a Stand-Alone Library".

This should include step by step instructions required to follow to install and use the library. For example, it can look something like this:
1. Untar blah.x.x.tar.gz to /path/to/docroot/blah
2. Add the following code to your include path:
<? 
  ...
?>
3. Confirm library is correctly installed by running blah.helloworld.php. If everything installed properly the script will return xyz.

Ideally, there would also be a similar section called "Getting Started: aura.router with the aura framework"

Also note that a short description of dependency injection, with a link or two perhaps, near the top of each library README, would also be helpful, IMO.

**Comment by harikt** [comment]
Hi Guys , 

I have written something about getting started . You can see the gist over 

https://gist.github.com/1065323

As examples are already provided in the Aura.\* Packages there is not a big deal to repeat it . What do you feel ?

**Comment by pmjones** [comment]
This has been added at http://auraphp.github.com/Aura.Router/
