### ISSUE TITLE
match method allows null for $server but it's required

### ISSUE THREAD

**Issue by jelofson** [auraphp/Aura.Router#24]
public function match($path, array $server = null) {
    ...
    // Then a call to $route->isMatch($path, $server);
}

So, either remove the null or use $_SERVER if null?

I can make a change if you think it's warranted. 

J.

**Comment by pmjones** [comment]
Aha!  Yes, patch please.  Thanks!

**Comment by pmjones** [comment]
Oh, and no use of $_SERVER; remove the null.

**Comment by jelofson** [comment]
You've done some really nice work there in Aura. Looking really good.

Jon

**Comment by pmjones** [comment]
This was fixed in the 1.1.0 release; thanks!

**Comment by harikt** [comment]
can we close this @pmjones ? I am closing this, for you mentioned it is fixed in 1.1.0 release.
