### ISSUE TITLE
PHP version compatibility query

### ISSUE THREAD

**Issue by rickmills** [auraphp/Aura.Router#26]
Hi,

Could I just check, other than PHP 5.4's new 'quick array' brackets ($array = [];) is there any other code in use that isn't php 5.3 compatible? I've been scouring through the source on github but cant see anything else other than the array brackets that would prevent php 5.3 compatibility.

**Comment by harikt** [comment]
Yes you are right.

There is only one place that it tries to accept either a callable behavior
or array . If you cannot use callable then you can only use array .

Apart from that there is nothing.

_Hari K T_

http://harikt.com , https://github.com/auraphp

**Comment by harikt** [comment]
@rmwebs we have been rethinking to make it 5.3 portable. Hope it will see some lights ;-) .

**Comment by jjok** [comment]
:thumbsup:

**Comment by harikt** [comment]
In a first look it seems like compatible with 5.3, but not really :-1:  . I am still looking into it.

**Comment by harikt** [comment]
I wonder whether it is really worth to make it 5.3 for the time we spend on these.

**Comment by pmjones** [comment]
The consensus so far is not to port it back to 5.3.  @rmwebs if you like, feel free to fork it, backport to 5.3, and I'll help you advertise it if you like.

**Comment by rickmills** [comment]
Just wanted to let you know for anyone who may want/need them, we've successfully backported Aura.Router, Aura.Http and Aura.Session to 5.3

Router: https://github.com/WHSuite/Aura.Router
Http: https://github.com/WHSuite/Aura.Http
Session: https://github.com/WHSuite/Aura.Session

We're using them in a project we're working on, so will be maintaining the forks above.

**Comment by harikt** [comment]
great! . We can make a note of 5.3 availability.
