### ISSUE TITLE
Language routes

### ISSUE THREAD

**Issue by adrianmiu** [auraphp/Aura.Router#34]
How does one set up language routes with Aura.Router? I want to match `/en/blog/read/1` and `/blog/read/1` with the same route but it seems I would need to set up 2 routes: one that is with the language prefix, the other without

```
$router->add('read', '/blog/read/{id}');
$router->add('lang_read', '/{lang}/blog/read/{id}');
```

Or there is another option?

**Comment by harikt** [comment]
@adrianmiu nice question.

I feel you always need to have the language prefix.

**Comment by adrianmiu** [comment]
I've looked at the code and for matching a route you can do something like

```
        $router
            ->add('generic', '(/?{language}?)/blog/read/{id}(\.?{type}?)')
            ->addTokens(array(
                'language' => '[a-z]{0,2}',
                'id' => '[^/\.]+'
            ))
            ->addValues(array(
                'language' => 'en',
                'type' => 'html'
            ));
        $routeFound = $this->router->match('/blog/read/5', array());
```

The route is matched but the generate function does not work.

**Comment by adrianmiu** [comment]
I've submitted a pull-request (#35) for this issue
