### ISSUE TITLE
Remembering matched route

### ISSUE THREAD

**Issue by djmattyg007** [auraphp/Aura.Router#37]
I was wondering if you'd accept a pull request to implement functionality that would mean the Router class (Aura\Router\Router) would remember whether or not it had attempted to match a route yet, and if so, which route it matched. I have a need for this functionality in something I'm developing, and it would make my life easier if the Aura.Router module did this by itself.

**Comment by harikt** [comment]
Hey @djmattyg007  you can see the `getDebug` method https://github.com/auraphp/Aura.Router/blob/fa94e4792593863c7cc807428f1e54331d0511bf/src/Router.php#L157 which has the array of routes tried. Hope that helps.

Thanks

**Comment by djmattyg007** [comment]
The problem with that approach is that if no routes are matched, the last item in the return array from getDebug() would still be a valid route.

**Comment by harikt** [comment]
Not sure I get you. Eg: 

``` php
$route = $router->match($path, $_SERVER);
$routes = $router->getDebug();
if (! $route) {
    // no route object was returned
    echo "No application route was found for that URL path.";
    // display these are the routes tried to match
} else {
   // routes that are tried to match
}
```

**Comment by djmattyg007** [comment]
In my application, I only keep the matched Route object around long enough to dispatch to the controller associated with that route. However, I keep the Router object alive for the duration of the request so that I can use it for its URL generation capabilities (specifically its generate() function. This means that your above example does not really apply to my situation.

Being able to check which route is the matched route has other applications too, such as highlighting the "active" tab or entry in a menu.

Passing around both the Router object and the Route object is incredibly inefficient, and it would be nice if it waa possible to access the matched Route object from the Router object.

**Comment by harikt** [comment]
That make sense to me. I am not sure @pmjones like the idea or not. So I don't guarantee that if a PR is send it  will be merged. Either you wait for Paul to respond, or send a PR in the mean while ( Feel it will not be a big issue ).
ok?

Thank you.
