### ISSUE TITLE
Extra slashes in route generation

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Router#42]
Consider a route like the below 

``` php
$router->add('archieve', '/archieve/{year}/{month}/{day}')
    ->addTokens([
        'year' => '[^/]+',
        'month' => '[^/]+',
        'day' => '[^/]+'
]);
```

When you try to generate route as

``` php
echo "<a href=\"" . $router->generate('archieve') . "\">Archieve</a>";
echo "<a href=\"" . $router->generate('archieve', ['year' => 2013]) . "\">Archieve</a>";
```

It generates something like `/archieve///` and `/archieve/2013//` . We should remove the `/` if the route has no more values after that.

**Comment by djmattyg007** [comment]
The parameters aren't optional though. I think a better idea would be to put a note in the documentation that generating a route without providing all of the compulsory parameters can result in unexpected behaviour would be a better idea.

**Comment by harikt** [comment]
@djmattyg007 no. I don't like the idea. Would like to fix it.
Didn't get enough time to dig into this.

**Comment by harikt** [comment]
Oh @djmattyg007 you are right on this. I thought I was using optional parameters. https://github.com/auraphp/Aura.Router#optional-params .
