### ISSUE TITLE
Latest update to the 1.x branch breaks 5.3 compatibility with shorthand arrays.

### ISSUE THREAD

**Issue by rickmills** [auraphp/Aura.Router#46]
The latest update in this commit: https://github.com/auraphp/Aura.Router/commit/0bcdaa1168b338a97ae3c7da8d5c607e13695236 breaks php 5.3 compatibility. Was this intentional or an oversight as the blogpost announcing the update states "you should be able to update-in-place without any problems" which wont be the case for anyone on 5.3.

I know 5.4 or above is desirable, but is it really worth killing off 5.3 over a handful of shorthand arrays? There's surely no need for that is there?

**Comment by harikt** [comment]
@rmwebs I thought Aura.Router v1 was not compatible with 5.3 . 

Aura.Router v2 is 5.3 compatible. Are you sure ?

**Comment by pmjones** [comment]
@rmwebs The 1.x libraries are targeted at 5.4; _some_ of the 2.x libraries have been pushed back to 5.3 for wider adoptability. However, I see your point, and converting [] to array() seems easy enough.  We'll keep the requirement at 5.4 but I'll see about making the change to allow 5.3.  Don't depend on this being the case in the future though.

**Comment by pmjones** [comment]
Hm, it looks like the short-array syntax has been in there for quite some time @rmwebs, at least since the last release. I'm not sure why the last release would have worked for you under 5.3. Can you give further commentary here?

**Comment by harikt** [comment]
oh @pmjones @rmwebs then I advertised Aura.Router v1 is compatible with 5.4 in sitepoint article year back I guess.

**Comment by harikt** [comment]
@pmjones iirc what I wrote was 5.3 compatibility for some other fork. So I don't think 5.3 compatible was in v1 anyway.

**Comment by pmjones** [comment]
Yeah, 2.x is 5.3 compatible, but 1.x is 5.4 and above only (and has been for a long time). @rmwebs if you have further info that would be helpful here.

**Comment by rickmills** [comment]
Hi guys,

Please accept my apologies. I don't know why but I was under the impression that 1.x was 5.3 compatible.

**Comment by pmjones** [comment]
No problem, and thanks for keeping an eye on BC issues. :-)

**Comment by harikt** [comment]
no apologies needed @rmwebs . Aura.Router v2 is 5.3 compatible. So you can always use the power of v2.

Thank you.
