### ISSUE TITLE
set a default value on each route

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Router#57]
Eg : When using a route which have a language it will be good to have a default language set in the router than adding it on each route.

```
$router->setDefaultParams(array('lang' => 'en', 'format' => '.html'))
```

so we don't need to add the default format, change the language on all routes. The idea is when a route add is called internally we can add to `addValues` what do you think ?

**Comment by pmjones** [comment]
This is the kind of thing end-users can set on their own; some may have different variables for languages,e tc.

**Comment by harikt** [comment]
I don't know whether you get me here or not.

If you have 10 routes, it becomes tedious to always have a language param. My idea is if we can do in a single place  and let the global values are always returned on each route params value.

**Comment by pmjones** [comment]
Yes, that's the point of the default values setting on the main router object. You can call, e.g., $router->addValues(array('lang' => 'en')) and all routes added thereafter will pick it up.

**Comment by harikt** [comment]
Thanks. That was what I need :) .
