### ISSUE TITLE
Without url encode in generate

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Router#58]
Is it possible to create urls without urlencode ?

Eg : in aura/asset-bundle when we pass the file path as `/css/something.css` all will be converted to %2Fcss%2Fsomething.css . That means even when we have the real path with some sort of file moved, the css may not get loaded.

Any idea to fix for routes like that ?

**Comment by pmjones** [comment]
That's an interesting issue. I assume it's because the value itself includes slashes (e.g., "path" => "/css/something.css"). The question then is, does it cause trouble later on, or does it just look ugly?

**Comment by harikt** [comment]
The url will be `%2Fcss%2Fsomething.css` which when read via the assets will not work. We may need to do urldecode in the asset bundle.

**Comment by pmjones** [comment]
> We may need to do urldecode in the asset bundle.

/me nods

Alternatively, do we want to change %2F back to / when doing url encode in the router? I don't know if that's a good idea or not.

**Comment by harikt** [comment]
The problem is 

``` php
<link rel="stylesheet" href="<?php echo $this->router()
      ->generate('aura.asset',
          array(
              'vendor' => 'cocoframework',
              'package' => 'example',
              'file' => '/css/poole.css'
          )
      ); ?>">
```

`http://cocoframework.localhost/asset/cocoframework/example/%2Fcss%2Fpoole.css` when requested in browser gives a 404 .

``` php
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /asset/cocoframework/example//css/poole.css was not found on this server.</p>
<hr>
<address>Apache/2.2.22 (Ubuntu) Server at cocoframework.localhost Port 80</address>
</body></html>
```

> Alternatively, do we want to change %22 back to / when doing url encode in the router? I don't know if that's a good idea or not.

I don't know what you were looking for :( .

Taking the route from https://github.com/harikt/Aura.Asset_Bundle/blob/master/config/Common.php#L28-L34

``` php
 $router->add('aura.asset', '/asset/{vendor}/{package}/{file}')
->setValues([
'action' => 'aura.asset',
])
->addTokens(array(
'file' => '(.*)'
));
```

**Comment by pmjones** [comment]
Yeah, so what I'm saying is that maybe we should ...
1. Apply urlencode() like we do already, and then
2. str_replace('%2F', '/', $value)

... then replace the token with that value. The idea is that we url encode everything _except_ slashes.

(An alternative would be to explode the value on slashes, url encode each piece, then implode with slashes.)

Does that make sense?

**Comment by harikt** [comment]
Got it. Not sure whether it is right / wrong. But it will work I guess :) .

**Comment by pmjones** [comment]
Hey, can you send me the route code you are using to point to the asset bundle? I want to try some stuff out.

**Comment by pmjones** [comment]
Just this, yes? https://github.com/pmjones/Aura.Asset_Bundle/blob/master/config/Common.php#L29-L35

**Comment by harikt** [comment]
@pmjones yes. That is the route code. Nothing more.

**Comment by harikt** [comment]
@pmjones can we move the asset bundle to @auraphp organization ? 

Edit : may be name it as Aura.AssetBundle ?

**Comment by pmjones** [comment]
OK, @harikt , check out the new [genraw](https://github.com/auraphp/Aura.Router/tree/genraw) branch. The generate() method now takes an optional third param, an array of keys to be left raw.

https://github.com/auraphp/Aura.Router/blob/genraw/src/Generator.php#L44-L58

So you could call `generate('route.name', array('file' => 'styles/blog.css'), array('file'))` to prevent encoding of the file value.

It's kind of hackish, so I'm open to other ideas.

**Comment by pmjones** [comment]
Closed per the new generateRaw() method. Thanks @harikt for talking this out with me.
