### ISSUE TITLE
In readme

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Router#6]
In the advanced section 

`method -- The $server['REQUEST_METHOD'] must match one of these values.`
`secure -- When true the $server['HTTPS']` ,

I feel its $_SERVER , but as I am confused whether you was trying to represent the variable in signature function over 

`is_match -- A custom callback or closure with the signature function(array $server, \ArrayObject $matches)`

Sample code I tried is not working , confusion over the `format` in documentation . See first example no dot for format , second one has dot for the format . I feel we don't need the dot to be passed . Do you feel so ? Then why ? Normally we say html , atom like so , not .html , .xml etc .

```
<?php
$package_dir = dirname( __DIR__ ) . '/auraphp/system/package';
$loader = require_once $package_dir . '/Aura.Autoload/scripts/instance.php';
$loader->add('Aura\Router', $package_dir . '/Aura.Router/src/' );
$loader->register();
use Aura\Router\Map;
use Aura\Router\RouteFactory;
$map = new Map(new RouteFactory);
/*
$map->add('home', '/');
$map->add(null, '/{:controller}/{:action}/{:id}');
$map->add('read', '/blog/read/{:id}{:format}', [
    'params' => [
        'id' => '(\d+)',
        'format' => '(\..+)?',
    ],
    'values' => [
        'controller' => 'blog',
        'action' => 'read',
        'format' => '.html',
    ]
]);
*/
$map->add('read', '/blog/read/{:id}{:format}', [
    'params' => [
        'id' => '(\d+)',
        'format' => '(\..+)?',
    ],
    'values' => [
        'controller' => 'blog',
        'action' => 'read',
        'id' => 1,
        'format' => '.html',
    ],
    'secure' => false,
    'method' => ['GET'],
    'routable' => true,
    'is_match' => function(array $server, \ArrayObject $matches) {

        // disallow matching if referred from example.com
        if ($server['HTTP_REFERER'] == 'http://example.com') {
            return false;
        }

        // add the referer from $server to the match values
        $matches['referer'] = $server['HTTP_REFERER'];
        return true;

    },
    'generate' => function(\Aura\Router\Route $route, array $data) {
        $data['foo'] = 'bar';
        return $data;
    }
]);

$path = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);

$route = $map->match($path, $_SERVER);
if (! $route) {
    // no route object was returned
    echo "No application route was found for that URI path.";
    exit;
}
echo " Controller : " . $route->values['controller'];
echo " Action : " . $route->values['action'];
echo " Format : " . $route->values['format'];
```

I have started the server with 

```
$ php -s localhost:8000 
```

from the default directory . I guess, the error is throwing by Apache and not by Router itself .

**Comment by harikt** [comment]
In the format 

```
        'params' => [
            'id'     => '(\d+)',
            'format' => '(\.json|\.atom)?'
        ],
        'values' => [
            'format' => '.html',
        ],
```

I don't think we need the dot , can we remove that if so ?

**Comment by harikt** [comment]
Do we need to create any .htaccess file ? The path http://localhost:8000/blog/read/1 is ok , but when a .html or .json is added it just throws Not Found .

**Comment by harikt** [comment]
@pmjones  may be you want to investigate into this before we go for next release . I feel its due to my php installation issue , but not sure though.
Thank you

**Comment by pmjones** [comment]
Regarding `$server` vs `$_SERVER`, the use of `$server` is to indicate the object property, as vs the PHP superglobal.  The `$server` property gets populated from the globals, but its value may change independently of `$_SERVER`.

**Comment by pmjones** [comment]
There's a bug in Route::isSecureMatch(); it uses = when it should use ==. Fixing and testing now, and adding debugging/logging methods so other problems will be easier to diagnose.

**Comment by pmjones** [comment]
Fixed, committed, and pushed.  Try it again; if you still have trouble, please open a new issue. Thanks HariKT !

**Comment by harikt** [comment]
@pmjones opened issue #7 . Not sure whether its with some php configuration issue .
