### ISSUE TITLE
Configuring the router with an array

### ISSUE THREAD

**Issue by mnapoli** [auraphp/Aura.Router#64]
Hi there!

I've been using Aura's router a tiny bit (still at noob level to be honest) and the first thing I did was write something that allows me to configure the routes using an array. Example (from [here](https://github.com/mnapoli/Maintained/blob/master/app/config/routes.php)):

``` php
$routes = [
    'home'    => [
        'pattern'    => '/',
        'controller' => HomeController::class,
    ],
    'project' => [
        'pattern'    => '/project/{user}/{repository}',
        'controller' => ProjectController::class,
    ],
];

// Then later on:
$router = (new RouterFactory())->newInstance();
foreach ($routes as $routeName => $route) {
    $router->add($routeName, $route['pattern'])
        ->addValues(['controller' => $route['controller']]);
}
```

This is of course very basic, but I was wondering if you have ever considered and discussed something like that. I guess that wouldn't fit everybody's usage, but for my usage, that's the only way I would use a router as soon as I get more than 2 routes.

**Comment by harikt** [comment]
Hey @mnapoli , 

I did noticed your code some days back and was thinking about it. My first thought was you could have used something like usage in cache. https://github.com/auraphp/Aura.Router/#caching-route-information . But later I understood that was not the way we need.

Anyway I am not against this, but we can hear from Paul what he thinks.

**Comment by harikt** [comment]
So just something strikes me. If we are doing something like this, that makes missing a few usage calling different methods on the route. See 

``` php
$router->add('blog.read', '/blog/read/{id}{format}')
    ->addTokens(array(
        'id'     => '\d+',
        'format' => '(\.[^/]+)?',
    ))
    ->addValues(array(
        'action'     => 'BlogReadAction',
        'format'     => '.html',
    ));
```

That make me feel we may not be adding it :-1:  . Anyway ie into the court of Paul  .

**Comment by mnapoli** [comment]
> that makes missing a few usage calling different methods on the route.

As I said, my example was just very basic, it's just to illustrate the thing. A serious implementation should of course cover all the features.

**Comment by harikt** [comment]
aah ok :+1:  . Either you can wait for @pmjones to answer or can send a PR . He will merge if things are found satisfactory. 

By the way @mnapoli can you keep any aura project on the maintained home page ;-) . If not possible no deal :-) . Just asked. 

And thank you for using aura.

**Comment by mnapoli** [comment]
I added Aura.Sql as it seems to be the most popular project for now so the numbers are meaningful.

**Comment by harikt** [comment]
Thank you @mnapoli .

**Comment by dhaaker** [comment]
I think @mnapoli means something like the "Constructor-Time Attachment" option Aura.Router v1 provided (http://auraphp.com/packages/Aura.Router/1.2.0/).

**Comment by harikt** [comment]
@dhaaker thanks . I forgot about it .

**Comment by mnapoli** [comment]
@dhaaker oh yeah that looks totally like what I'm trying to do

**Comment by pmjones** [comment]
> I was wondering if you have ever considered and discussed something like that.

Hi @mnapoli -- as noted above, yeah, this is something we did in v1. In fact it was the _only_ way to configure the router in v1. It ended up being quite unwieldy. Among other things, it became difficult to construct the array descriptor in a way that covered Every Possible Condition Ever. It's not the kind of thing I'd want to try my hand at again.

Having said that, if you want to add a method on the RouterFactory that takes an array descriptor of the kind you mention and translates it into a RouteCollection for the Router, I will be happy to review it. I warn you, though, it's going to be quite the undertaking.

With all that in mind, is this issue still something high on your list? (If not, I'd like to close it and move on.)

Finally, thanks for taking the time to use (or at least review) the library. :-)

**Comment by harikt** [comment]
@pmjones FYI : router is used in http://isitmaintained.com/

**Comment by mnapoli** [comment]
OK I see your point, thanks for the feedback!
