### ISSUE TITLE
Optional parameters not working as expected?

### ISSUE THREAD

**Issue by jamesaspence** [auraphp/Aura.Router#65]
Hey guys, I have optional parameters set in a URL as follows:

```
$routes = [
    [
        "name" => "API",
        "path" => "/api/{version}/{class}{/id,function,third}/"
    ]
];

$newRoute = $this->router->add($route["name"], $route["path"]);
    if(isset($route["tokens"]))
        $newRoute->addTokens($route["tokens"]);
    if(isset($route["values"]))
        $newRoute->addValues($route["values"]);
```

and I have the controller matching it printing it out like this:

```
if(isset($this->route->params["id"]))
    echo "id = " . $this->route->params["id"] . "<br><br>";
if(isset($this->route->params["function"]))
    echo "function = " . $this->route->params["function"] . "<br><br>";
if(isset($this->route->params["third"]));
    echo "third = " . $this->route->params["third"] . "<br><br>";
exit;
```

So that if you have a URL like /api/1/class/id/function/third/, it'll print out like:

```
id = id
function = function
third = third
```

however, if I only specify a single parameter (i.e. /api/1/class/id/), it will still print like this:

```
id = id
third = 
```

So it always sets third, regardless of whether or not it's been specified.
Anybody know why? Is it my syntax that's causing the issue?

**Comment by harikt** [comment]
This is where you are doing wrong .

`if(isset($this->route->params["third"]));`

See the `;` . Consider coding with PSR-1, PSR-2 so your if always have `{` and ending `}` .

Thank you.

**Comment by harikt** [comment]
The best way to look is `var_dump($route->params);` . Some may argue not to use var_dump though ;) .

**Comment by jamesaspence** [comment]
Welp.. I feel dumb.
Thanks for the help!

**Comment by harikt** [comment]
You are welcome :+1:  .

**Comment by pmjones** [comment]
Wow, @harikt , that's a great great catch. I would not have seen that.

@ThaPastafarian As noted by @harikt PSR-2 will save you here. Specifically, _always always always_ use braces on if/else bodies. The habit of doing so will save you much time and frustration.

**Comment by harikt** [comment]
I did tried myself ;) . Just looking at code have not helped me also :-) . Yes PSR-2 will help a lot in these cases.
