### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Router#70]
Hi @auraphp/code-team , 

I have been thinking a lot on how not to use phpunit.sh for there can be people who use Windows.

I love to change the current way of using phpunit.sh to test containers with `require-dev` in composer.

We can add `aura/di` into require-dev and users can install the packages with `--no-dev` for production.

And now if you are going to test or write a PR .

``` bash
composer install --dev
phpunit -c tests/unit
phpunit -c tests/container
```

This seems to be nice. Also we could promote the use of `--no-dev` .

Thank you.

**Comment by pmjones** [comment]
I am very, very much against the idea of having a "require-dev" in there. It looks too much like a dependency, even though we know it's for testing only.

**Comment by harikt** [comment]
@pmjones require-dev is only for development. None assume it is need to use in production .

And I feel it is time to promote the good culture :) . About the feeling we can change it when it is promoted.

**Comment by pmjones** [comment]
All right, let me review it some more. Maybe this will be a good way to integrate the container tests under a single testing process.
