### ISSUE TITLE
Hability to cut matched patterns

### ISSUE THREAD

**Issue by guilhermeaiolfi** [auraphp/Aura.Router#71]
It's extra useful for things like format/output as used in the README example. Once you can set that a route should be `cut`, it will continue trying to find a route that matches but without the cut part. An example:

```
$router->add(
    'output',
    '{format}',
     ->cut()
     ->addTokens(array(
        'format' => '(\.[^/]+)?',
    ));
$router->add(
    'blog.read',
    '/blog/{id}',
     ->addTokens(array(
        'id' => '\d+',
    ));
```

that would make `blog.read` match in any of the cases:

```
/blog/12.json
/blog/12.html
/blog/12.xml
```

**Comment by harikt** [comment]
Hey @guilhermeaiolfi ,

My assumption is this is still possible without cut . See https://github.com/auraphp/Aura.Router/blob/3ffbab7da1de0f691af5daf949a1f2c879cae362/tests/unit/src/RouteTest.php#L58-L77

Try this 

``` php
$router->add('blog.read','/blog/{id}{format}')
            ->setTokens(array(
                'id' => '([0-9]+)',
                'format' => '(\.[^/]+)?',
            ))
            ->setValues(array(
                'format' => '.html',
            ));
```

**Comment by guilhermeaiolfi** [comment]
Sure, but then you have to include `{format}` in every route you have.

**Comment by harikt** [comment]
may be not magics ;) . Anyway I am not sure whether there is any other way. I wonder about the callable part though whether it can handle any.

**Comment by guilhermeaiolfi** [comment]
My idea creating this issue was more towards a feature request. If you think it's a acceptable feature I could give it a try and implement it myself. I'm not familiarized with the codebase (I started using aura router two weeks ago) so it could take some time and guidance.

**Comment by harikt** [comment]
>  If you think it's a acceptable feature I could give it a try and implement it myself.

You may need to wait to hear from @pmjones . I wonder whether it is really needed or not, may be it is good to expose the route variables in that way the `setRouteCallable` can be applied ?

An example is https://github.com/auraphp/Aura.Router/pull/47 . 

If you like send a PR so when he is back after #phpworld he can look into this.

**Comment by guilhermeaiolfi** [comment]
`setRouteCallable` gets a route as argument, so I think its scope is just the route. To cut the URL, the router and the path being parsed would have to be available. Looking at the code, I think just a few lines in `Router::match` and a `setCut` method in `Route` would be enough. I'll wait to hear from @pmjones and see what he thinks.

**Comment by pmjones** [comment]
I appreciate the thinking here @guilhermeaiolfi but I find it easy to imagine problems. As noted by @harikt, I think explicitness is thing to go for. Sorry to disappoint you. :-(
