### ISSUE TITLE
Router README.MD Ataching Route Groups

### ISSUE THREAD

**Issue by miferval** [auraphp/Aura.Router#74]
On the README.MD on the example regarding Attaching Route Groups the code should be

$name_prefix = 'blog';
$path_prefix = '/blog';

$router->attach($name_prefix, $path_prefix, function ($router) {

```
$router->add('browse', '{format}')
    ->addTokens(array(
        'format' => '(\.json|\.atom|\.html)?'
    ))
    ->addValues(array(
        'format' => '.html',
    ));

$router->add('read', '/{id}{format}')
    ->addTokens(array(
        'id'     => '\d+',
        'format' => '(\.json|\.atom|\.html)?'
    ))
    ->addValues(array(
        'format' => '.html',
    ));

$router->add('edit', '/{id}/edit{format}')
    ->addTokens(array(
        'id' => '\d+',
        'format' => '(\.json|\.atom|\.html)?'
    ))
    ->setValues(array(
        'format' => '.html',
    ));
```

});

**Comment by harikt** [comment]
@miferval not sure what you are looking for. Could you expand? Is there something wrong ? If so please send a PR if you can, else you can comment. We will fix .

Thank you.

**Comment by miferval** [comment]
In the README.md on the Attaching Route Groups Example, I think I spot some errors. On the code below on line 11 at the end of the line   ", array("   instead of   ")"
same on line 20
And in line 15 at the end of the line there is a comma that should not be there

1 - $router->attach($name_prefix, $path_prefix, function ($router) {
2 -
3 -   $router->add('browse', '{format}')
4 -        ->addTokens(array(
5 -           'format' => '(.json|.atom|.html)?'
6 -        ))
7 -        ->addValues(array(
8 -            'format' => '.html',
9 -        ));
10-
11-    $router->add('read', '/{id}{format}', array(
12-        ->addTokens(array(
13-            'id'     => '\d+',
14-            'format' => '(.json|.atom|.html)?'
15-        )),
16-        ->addValues(array(
17-            'format' => '.html',
18-        ));
19-
20-    $router->add('edit', '/{id}/edit{format}', array(
21-        ->addTokens(array(
22-            'id' => '\d+',
23-            'format' => '(.json|.atom|.html)?'
24-        ))
25-        ->addValues(array(
26-            'format' => '.html',
27-        ));
28- });

Great Work
Regards

**Comment by harikt** [comment]
You are right . Could you send a PR to fix the same? Credits will be shown over http://auraphp.com/community

**Comment by harikt** [comment]
Closing as of #75 merged.

Thank you for reporting and sending the PR.
