### ISSUE TITLE
Trailing slashes shouldn't blow up

### ISSUE THREAD

**Issue by brandonsavage** [auraphp/Aura.Router#79]
Right now, if I define a route that does not explicitly contain a trailing slash, and then I use one, it won't match.

E.g. route defined is /home, but I go to example.com/home/, I get a 404.

**Comment by harikt** [comment]
#4 will not fix .

**Comment by graphis** [comment]
Sorry I know this is a closed discussion, but what is the case with the following two scenarios?

'/page/{page}?'
domain.com/page/yourname = 202
domain.com/page/                 = 202
domain.com/page                  = 404   // although there is a default value for {page} specified

'/page{/page}?'
domain.com/page/yourname = 404
domain.com/page/                 = 202
domain.com/page                  = 202

**Comment by harikt** [comment]
Hi @graphis ,

Please consider opening a new issue if you have any problem. 

I did noticed something strange in this. Consider sending a test case to reflect the issue to appropriate branch, so we have a failing test case.

Thank you
