### ISSUE TITLE
Add "domain" or "host" as a matching constraint

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Router#83]
Currently I don't know whether we can make an option like make use of different controller for different sub domain.

``` php
$router->add('blog.browse', '/blog')
    ->addValues(array(
        'action'     => 'BlogBrowseAction',
    ))
    ->addDomain('*.hello.com');
$router->add('m.blog.browse', '/blog')
    ->addValues(array(
        'action'     => 'BlogMobileBrowseAction',
    ))
    ->addDomain('m.hello.com');
```

We can do in 2.x with adding a callable, but may be the controller and params may not be able to change 

``` php
->setIsMatchCallable(function(array $server, \ArrayObject $matches) {
        if ($server['HTTP_HOST'] == 'http://example.com') {
            return false;
        }
    })
```

Thank you

**Comment by pmjones** [comment]
I think that's a good idea for 3.x, and maybe even for 2.x.

**Comment by pmjones** [comment]
This has been added in 3.x. If you think it needs to be in 2.x as well, or want to back port it, please open a PR. Thanks @harikt !
