### ISSUE TITLE
Multiple hosts

### ISSUE THREAD

**Issue by kristoftorfs** [auraphp/Aura.Router#95]
Instead of allowing a single host, it could be handy to match more than one e.g. when multiple domains are used.

**Comment by pmjones** [comment]
(/me tilts head) Can you show an example of what you mean?

**Comment by kristoftorfs** [comment]
Nevermind, just went over the docs again, and noticed that I can use regular expressions in the Router->host method. Been a long day... :-)

What I meant was that I wanted to create routes constrained to mydomain.com as well as myseconddomain.com and I thought I would have to duplicate each route for every domain.

**Comment by pmjones** [comment]
Good deal. :-)
