### ISSUE TITLE
Generating absolute urls?

### ISSUE THREAD

**Issue by ChrisTitos** [auraphp/Aura.Router#97]
Hi, I'm trying out version 3.
It's possible to specify matching constraints on routes for hosts/subdomains. But I can't find the possibility to then generate these routes? For example I want to generate a url with a specific subdomain. But you only get the path.

Is it possible to add this feature?

**Comment by pmjones** [comment]
Mmm, that's a good question. I can't think off-hand how to add this, but it sounds like a neat idea. If you can submit a PR, I'll be happy to review it. Also, if you have examples of other libs that generate with domains, that might help me think of something.

**Comment by harikt** [comment]
I am looking at https://github.com/symfony/Routing/blob/master/Tests/Generator/UrlGeneratorTest.php#L396 . 

Edit : You can search for example.com from the page and there are more tests for different functionality.

**Comment by pmjones** [comment]
Aha! It looks like in 3.x we can modify the Generator to honor the `$route->host` value, if it is present. @ChrisTitos @harikt would that work for you?

**Comment by pmjones** [comment]
Hell, we might even be able to honor the `$route->secure` value as well (i.e., http vs https). Thoughts?

**Comment by harikt** [comment]
> Hell, we might even be able to honor the $route->secure value as well (i.e., http vs https)

:+1:  and default to http ?

Edit : Default to http for if the route is defined on another host which is not secure. Not sure what the right way is. May be depending on the current url itself.

**Comment by ChrisTitos** [comment]
Sounds great. I think if you want absolute urls as a dev you just need to make sure you have default host/secure values for your routes/map. Default http also seems reasonable.
I think Symfony uses the current request as default values, but with PSR-7 the request object could be changed, unless you pass it to the generator each time you want to generate a url? But that's quite annoying.

**Comment by pmjones** [comment]
I think we can avoid passing the request object entirely. For a `/foo/bar` path, prefixing an extra leading slash default to the current protocol (`//foo/bar`), which would be the case for `$secure === null`; when `$secure === true` we can additionally prefix with `https:`, and then `$secure===false` we can additionally prefix with `http:`.

Thanks for this issue, I think I can work up a fix today or tomorrow!

**Comment by pmjones** [comment]
@ChrisTitos Take a look at #99 and tell me if it fits your needs. (cc @harikt)
